/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProposalsRouteImport } from './routes/proposals'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as ClientSetupRouteImport } from './routes/client-setup'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProposalsNewRouteImport } from './routes/proposals.new'
import { Route as ProjectsIdRouteImport } from './routes/projects.$id'
import { Route as InvoicesNewRouteImport } from './routes/invoices.new'
import { Route as ClientsIdRouteImport } from './routes/clients.$id'
import { Route as PortalProjectsIdRouteImport } from './routes/portal.projects.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsRoute = ProposalsRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientSetupRoute = ClientSetupRouteImport.update({
  id: '/client-setup',
  path: '/client-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalsNewRoute = ProposalsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProposalsRoute,
} as any)
const ProjectsIdRoute = ProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProjectsRoute,
} as any)
const InvoicesNewRoute = InvoicesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => InvoicesRoute,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ClientsRoute,
} as any)
const PortalProjectsIdRoute = PortalProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/client-setup': typeof ClientSetupRoute
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/proposals': typeof ProposalsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/clients/$id': typeof ClientsIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/proposals/new': typeof ProposalsNewRoute
  '/portal/projects/$id': typeof PortalProjectsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/client-setup': typeof ClientSetupRoute
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/proposals': typeof ProposalsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/clients/$id': typeof ClientsIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/proposals/new': typeof ProposalsNewRoute
  '/portal/projects/$id': typeof PortalProjectsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/client-setup': typeof ClientSetupRoute
  '/clients': typeof ClientsRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/invoices': typeof InvoicesRouteWithChildren
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/projects': typeof ProjectsRouteWithChildren
  '/proposals': typeof ProposalsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/clients/$id': typeof ClientsIdRoute
  '/invoices/new': typeof InvoicesNewRoute
  '/projects/$id': typeof ProjectsIdRoute
  '/proposals/new': typeof ProposalsNewRoute
  '/portal/projects/$id': typeof PortalProjectsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/client-setup'
    | '/clients'
    | '/dashboard'
    | '/invoices'
    | '/login'
    | '/portal'
    | '/projects'
    | '/proposals'
    | '/settings'
    | '/signup'
    | '/clients/$id'
    | '/invoices/new'
    | '/projects/$id'
    | '/proposals/new'
    | '/portal/projects/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/client-setup'
    | '/clients'
    | '/dashboard'
    | '/invoices'
    | '/login'
    | '/portal'
    | '/projects'
    | '/proposals'
    | '/settings'
    | '/signup'
    | '/clients/$id'
    | '/invoices/new'
    | '/projects/$id'
    | '/proposals/new'
    | '/portal/projects/$id'
  id:
    | '__root__'
    | '/'
    | '/client-setup'
    | '/clients'
    | '/dashboard'
    | '/invoices'
    | '/login'
    | '/portal'
    | '/projects'
    | '/proposals'
    | '/settings'
    | '/signup'
    | '/clients/$id'
    | '/invoices/new'
    | '/projects/$id'
    | '/proposals/new'
    | '/portal/projects/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClientSetupRoute: typeof ClientSetupRoute
  ClientsRoute: typeof ClientsRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  InvoicesRoute: typeof InvoicesRouteWithChildren
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  ProjectsRoute: typeof ProjectsRouteWithChildren
  ProposalsRoute: typeof ProposalsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals': {
      id: '/proposals'
      path: '/proposals'
      fullPath: '/proposals'
      preLoaderRoute: typeof ProposalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-setup': {
      id: '/client-setup'
      path: '/client-setup'
      fullPath: '/client-setup'
      preLoaderRoute: typeof ClientSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposals/new': {
      id: '/proposals/new'
      path: '/new'
      fullPath: '/proposals/new'
      preLoaderRoute: typeof ProposalsNewRouteImport
      parentRoute: typeof ProposalsRoute
    }
    '/projects/$id': {
      id: '/projects/$id'
      path: '/$id'
      fullPath: '/projects/$id'
      preLoaderRoute: typeof ProjectsIdRouteImport
      parentRoute: typeof ProjectsRoute
    }
    '/invoices/new': {
      id: '/invoices/new'
      path: '/new'
      fullPath: '/invoices/new'
      preLoaderRoute: typeof InvoicesNewRouteImport
      parentRoute: typeof InvoicesRoute
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof ClientsRoute
    }
    '/portal/projects/$id': {
      id: '/portal/projects/$id'
      path: '/projects/$id'
      fullPath: '/portal/projects/$id'
      preLoaderRoute: typeof PortalProjectsIdRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface ClientsRouteChildren {
  ClientsIdRoute: typeof ClientsIdRoute
}

const ClientsRouteChildren: ClientsRouteChildren = {
  ClientsIdRoute: ClientsIdRoute,
}

const ClientsRouteWithChildren =
  ClientsRoute._addFileChildren(ClientsRouteChildren)

interface InvoicesRouteChildren {
  InvoicesNewRoute: typeof InvoicesNewRoute
}

const InvoicesRouteChildren: InvoicesRouteChildren = {
  InvoicesNewRoute: InvoicesNewRoute,
}

const InvoicesRouteWithChildren = InvoicesRoute._addFileChildren(
  InvoicesRouteChildren,
)

interface PortalRouteChildren {
  PortalProjectsIdRoute: typeof PortalProjectsIdRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalProjectsIdRoute: PortalProjectsIdRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface ProjectsRouteChildren {
  ProjectsIdRoute: typeof ProjectsIdRoute
}

const ProjectsRouteChildren: ProjectsRouteChildren = {
  ProjectsIdRoute: ProjectsIdRoute,
}

const ProjectsRouteWithChildren = ProjectsRoute._addFileChildren(
  ProjectsRouteChildren,
)

interface ProposalsRouteChildren {
  ProposalsNewRoute: typeof ProposalsNewRoute
}

const ProposalsRouteChildren: ProposalsRouteChildren = {
  ProposalsNewRoute: ProposalsNewRoute,
}

const ProposalsRouteWithChildren = ProposalsRoute._addFileChildren(
  ProposalsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClientSetupRoute: ClientSetupRoute,
  ClientsRoute: ClientsRouteWithChildren,
  DashboardRoute: DashboardRoute,
  InvoicesRoute: InvoicesRouteWithChildren,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  ProjectsRoute: ProjectsRouteWithChildren,
  ProposalsRoute: ProposalsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
